#!/usr/bin/env bash

source colors.sh
if [ -n "$PS1" ]; then
    echo -e "${cyan}INTERACTIVE MODE.${reset}"

    if [ "$(uname)" = "Darwin" ];
    then
        read -p "Do you want to install software for mac? (y/n): " yn
        case $yn in
            [Yy]* ) ./mac_software_install.sh;;
            * ) echo "Skipping software installation"
        esac
    elif [ "$(uname)" = "Linux" ];
    then
        read -p "Do you want to install software for Linux? (y/n): " yn
        case $yn in
            [Yy]* ) ./linux_software_install.sh;;
            * ) echo "Skipping software installation"
        esac
    fi
fi

source symlink.sh
