# Luna color theme for tmux
# palette: https://github.com/WTFox/luna.nvim/blob/main/lua/luna/palette.lua

bg="#060606"
bg_alt="#1c1c1c"
base0="#000000"
base1="#1c1c1c"
base2="#1f1f1f"
base3="#333333"
base4="#404040"
base5="#605958"
base6="#7c7c7c"
base7="#989898"
base8="#c7c7c7"
fg="#e4e4e8"
fg_alt="#a8a8a8"
selected_fg=${base5}

coral="#c2916a"
gold="#d9a35a"
olive="#6fbe80"
steel="#75a1c7"
rose="#e08585"
sage="#9eb38e"
mauve="#c4a8d6"

# Basic status bar colors
set -g status-style bg=default,fg=${selected_fg}

# Left side of status bar
set -g status-left "#[fg=${sage}] #S #[fg=${selected_fg}]| "

# Right side of status bar
set -g status-right "#[fg=${coral}]#{battery_should_charge} #[fg=${selected_fg}]#{b:pane_current_path} | %m/%d %R | #{battery_percentage}"

# Window with activity status
set -g window-status-current-style bg=default,fg=${coral}
set -g window-status-bell-style bg=default,fg=${gold}

# Pane Borders
set -g pane-active-border-style bg=default,fg=${coral}
set -g pane-border-status off
set -g pane-border-style bg=default,fg=${base4}

# Clock mode
set -g clock-mode-colour ${coral}

# Mode (while highlighting text)
set -g mode-style bg=${coral},fg=${fg}

set -g display-panes-colour ${coral}
set -g display-panes-active-colour ${olive}
